-- ================================================================
-- 데일리 말씀 성경 구절을 한 절 전체 본문으로 교체
--
-- 기존 200건 중 성경 구절 140건은 앞부분만 담겨 있거나("하나님의 말씀은
-- 살아 있고 활력이 있어." — 히 4:12) 표현이 개역개정과 달랐다. 대한성서공회
-- 개역개정(한국어)과 World English Bible(영어, 퍼블릭 도메인) 본문을 받아
-- 각 절을 통째로 다시 넣는다. 인용 구절(quote) 60건은 건드리지 않는다.
-- ================================================================

update public.daily_verses dv
set text_kr = v.kr, text_en = v.en
from (values
  (1, '태초에 하나님이 천지를 창조하시니라 (창세기 1:1)', 'In the beginning, God created the heavens and the earth. (Genesis 1:1)'),
  (2, '여호와는 나의 목자시니 내게 부족함이 없으리로다 (시편 23:1)', 'Yahweh is my shepherd: I shall lack nothing. (Psalm 23:1)'),
  (3, '사랑하지 아니하는 자는 하나님을 알지 못하나니 이는 하나님은 사랑이심이라 (요한일서 4:8)', 'He who doesn’t love doesn’t know God, for God is love. (1 John 4:8)'),
  (4, '너희는 세상의 빛이라 산 위에 있는 동네가 숨겨지지 못할 것이요 (마태복음 5:14)', 'You are the light of the world. A city located on a hill can’t be hidden. (Matthew 5:14)'),
  (5, '내게 능력 주시는 자 안에서 내가 모든 것을 할 수 있느니라 (빌립보서 4:13)', 'I can do all things through Christ, who strengthens me. (Philippians 4:13)'),
  (6, '오직 그만이 나의 반석이시요 나의 구원이시요 나의 요새이시니 내가 흔들리지 아니하리로다 (시편 62:6)', 'He alone is my rock and my salvation, my fortress. I will not be shaken. (Psalm 62:6)'),
  (7, '내가 네게 명령한 것이 아니냐 강하고 담대하라 두려워하지 말며 놀라지 말라 네가 어디로 가든지 네 하나님 여호와가 너와 함께 하느니라 하시니라 (여호수아 1:9)', 'Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go. (Joshua 1:9)'),
  (8, '여호와를 의지하는 자는 시온 산이 흔들리지 아니하고 영원히 있음 같도다 (시편 125:1)', 'Those who trust in Yahweh are as Mount Zion, which can’t be moved, but remains forever. (Psalm 125:1)'),
  (9, '수고하고 무거운 짐 진 자들아 다 내게로 오라 내가 너희를 쉬게 하리라 (마태복음 11:28)', 'Come to me, all you who labor and are heavily burdened, and I will give you rest. (Matthew 11:28)'),
  (10, '두려워하지 말라 내가 너와 함께 함이라 놀라지 말라 나는 네 하나님이 됨이라 내가 너를 굳세게 하리라 참으로 너를 도와 주리라 참으로 나의 의로운 오른손으로 너를 붙들리라 (이사야 41:10)', 'Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness. (Isaiah 41:10)'),
  (11, '복음에는 하나님의 의가 나타나서 믿음으로 믿음에 이르게 하나니 기록된 바 오직 의인은 믿음으로 말미암아 살리라 함과 같으니라 (로마서 1:17)', 'For in it is revealed God’s righteousness from faith to faith. As it is written, “But the righteous shall live by faith.” (Romans 1:17)'),
  (12, '평강의 하나님께서 속히 사탄을 너희 발 아래에서 상하게 하시리라 (로마서 16:20)', 'And the God of peace will quickly crush Satan under your feet. The grace of our Lord Jesus Christ be with you. (Romans 16:20)'),
  (13, '여호와여 주의 이름을 아는 자는 주를 의지하오리니 이는 주를 찾는 자들을 버리지 아니하심이니이다 (시편 9:10)', 'Those who know your name will put their trust in you, for you, Yahweh, have not forsaken those who seek you. (Psalm 9:10)'),
  (14, '믿음이 없이는 하나님을 기쁘시게 하지 못하나니 하나님께 나아가는 자는 반드시 그가 계신 것과 또한 그가 자기를 찾는 자들에게 상 주시는 이심을 믿어야 할지니라 (히브리서 11:6)', 'Without faith it is impossible to be well pleasing to him, for he who comes to God must believe that he exists, and that he is a rewarder of those who seek him. (Hebrews 11:6)'),
  (15, '내가 여호와를 항상 내 앞에 모심이여 그가 나의 오른쪽에 계시므로 내가 흔들리지 아니하리로다 (시편 16:8)', 'I have set Yahweh always before me. Because he is at my right hand, I shall not be moved. (Psalm 16:8)'),
  (16, '그런즉 믿음, 소망, 사랑, 이 세 가지는 항상 있을 것인데 그 중의 제일은 사랑이라 (고린도전서 13:13)', 'But now faith, hope, and love remain—these three. The greatest of these is love. (1 Corinthians 13:13)'),
  (17, '나는 포도나무요 너희는 가지라 그가 내 안에, 내가 그 안에 거하면 사람이 열매를 많이 맺나니 나를 떠나서는 너희가 아무 것도 할 수 없음이라 (요한복음 15:5)', 'I am the vine. You are the branches. He who remains in me, and I in him, the same bears much fruit, for apart from me you can do nothing. (John 15:5)'),
  (18, '여호와는 나의 힘이요 노래시며 나의 구원이시로다 그는 나의 하나님이시니 내가 그를 찬송할 것이요 내 아버지의 하나님이시니 내가 그를 높이리로다 (출애굽기 15:2)', 'Yah is my strength and song. He has become my salvation. This is my God, and I will praise him; my father’s God, and I will exalt him. (Exodus 15:2)'),
  (19, '너희 염려를 다 주께 맡기라 이는 그가 너희를 돌보심이라 (베드로전서 5:7)', 'casting all your worries on him, because he cares for you. (1 Peter 5:7)'),
  (20, '그런즉 이 일에 대하여 우리가 무슨 말 하리요 만일 하나님이 우리를 위하시면 누가 우리를 대적하리요 (로마서 8:31)', 'What then shall we say about these things? If God is for us, who can be against us? (Romans 8:31)'),
  (21, '내가 산을 향하여 눈을 들리라 나의 도움이 어디서 올까 (시편 121:1)', 'I will lift up my eyes to the hills. Where does my help come from? (Psalm 121:1)'),
  (22, '그런즉 너희는 먼저 그의 나라와 그의 의를 구하라 그리하면 이 모든 것을 너희에게 더하시리라 (마태복음 6:33)', 'But seek first God’s Kingdom, and his righteousness; and all these things will be given to you as well. (Matthew 6:33)'),
  (23, '주의 말씀은 내 발에 등이요 내 길에 빛이니이다 (시편 119:105)', 'Your word is a lamp to my feet, and a light for my path. (Psalm 119:105)'),
  (24, '하나님의 말씀은 살아 있고 활력이 있어 좌우에 날선 어떤 검보다도 예리하여 혼과 영과 및 관절과 골수를 찔러 쪼개기까지 하며 또 마음의 생각과 뜻을 판단하나니 (히브리서 4:12)', 'For the word of God is living and active, and sharper than any two-edged sword, piercing even to the dividing of soul and spirit, of both joints and marrow, and is able to discern the thoughts and intentions of the heart. (Hebrews 4:12)'),
  (25, '여호와는 너를 지키시는 이시라 여호와께서 네 오른쪽에서 네 그늘이 되시나니 (시편 121:5)', 'Yahweh is your keeper. Yahweh is your shade on your right hand. (Psalm 121:5)'),
  (26, '사랑 안에 두려움이 없고 온전한 사랑이 두려움을 내쫓나니 두려움에는 형벌이 있음이라 두려워하는 자는 사랑 안에서 온전히 이루지 못하였느니라 (요한일서 4:18)', 'There is no fear in love; but perfect love casts out fear, because fear has punishment. He who fears is not made perfect in love. (1 John 4:18)'),
  (27, '평안을 너희에게 끼치노니 곧 나의 평안을 너희에게 주노라 내가 너희에게 주는 것은 세상이 주는 것과 같지 아니하니라 너희는 마음에 근심하지도 말고 두려워하지도 말라 (요한복음 14:27)', 'Peace I leave with you. My peace I give to you; not as the world gives, give I to you. Don’t let your heart be troubled, neither let it be fearful. (John 14:27)'),
  (28, '예수께서 이르시되 할 수 있거든이 무슨 말이냐 믿는 자에게는 능히 하지 못할 일이 없느니라 하시니 (마가복음 9:23)', 'Jesus said to him, “If you can believe, all things are possible to him who believes.” (Mark 9:23)'),
  (29, '예수께서 이르시되 내가 곧 길이요 진리요 생명이니 나로 말미암지 않고는 아버지께로 올 자가 없느니라 (요한복음 14:6)', 'Jesus said to him, I am the way, the truth, and the life. No one comes to the Father, except through me. (John 14:6)'),
  (30, '여호와의 말씀이니라 너희를 향한 나의 생각을 내가 아나니 평안이요 재앙이 아니니라 너희에게 미래와 희망을 주는 것이니라 (예레미야 29:11)', 'For I know the thoughts that I think toward you,” says Yahweh, “thoughts of peace, and not of evil, to give you hope and a future. (Jeremiah 29:11)'),
  (31, '그러나 이 모든 일에 우리를 사랑하시는 이로 말미암아 우리가 넉넉히 이기느니라 (로마서 8:37)', 'No, in all these things, we are more than conquerors through him who loved us. (Romans 8:37)'),
  (32, '그러므로 내가 너희에게 말하노니 무엇이든지 기도하고 구하는 것은 받은 줄로 믿으라 그리하면 너희에게 그대로 되리라 (마가복음 11:24)', 'Therefore I tell you, all things whatever you pray and ask for, believe that you have received them, and you shall have them. (Mark 11:24)'),
  (33, '그러므로 믿음은 들음에서 나며 들음은 그리스도의 말씀으로 말미암았느니라 (로마서 10:17)', 'So faith comes by hearing, and hearing by the word of God. (Romans 10:17)'),
  (34, '여호와의 손이 짧아 구원하지 못하심도 아니요 귀가 둔하여 듣지 못하심도 아니라 (이사야 59:1)', 'Behold, Yahweh’s hand is not shortened, that it can’t save; nor his ear dull, that it can’t hear. (Isaiah 59:1)'),
  (35, '내가 너희에게 분부한 모든 것을 가르쳐 지키게 하라 볼지어다 내가 세상 끝날까지 너희와 항상 함께 있으리라 하시니라 (마태복음 28:20)', 'teaching them to observe all things that I commanded you. Behold, I am with you always, even to the end of the age. Amen. (Matthew 28:20)'),
  (36, '내 영혼아 여호와를 송축하며 그의 모든 은택을 잊지 말지어다 (시편 103:2)', 'Praise Yahweh, my soul, and don’t forget all his benefits; (Psalm 103:2)'),
  (37, '여호와의 이름은 견고한 망대라 의인은 그리로 달려가서 안전함을 얻느니라 (잠언 18:10)', 'Yahweh’s name is a strong tower: the righteous run to him, and are safe. (Proverbs 18:10)'),
  (38, '주께서 생명의 길을 내게 보이시리니 주의 앞에는 충만한 기쁨이 있고 주의 오른쪽에는 영원한 즐거움이 있나이다 (시편 16:11)', 'You will show me the path of life. In your presence is fullness of joy. In your right hand there are pleasures forever more. (Psalm 16:11)'),
  (39, '너는 마음을 다하여 여호와를 신뢰하고 네 명철을 의지하지 말라 (잠언 3:5)', 'Trust in Yahweh with all your heart, and don’t lean on your own understanding. (Proverbs 3:5)'),
  (40, '네 생명을 파멸에서 속량하시고 인자와 긍휼로 관을 씌우시며 (시편 103:4)', 'who redeems your life from destruction; who crowns you with loving kindness and tender mercies; (Psalm 103:4)'),
  (41, '여호와께 감사하라 그는 선하시며 그의 인자하심이 영원함이로다 (시편 118:1)', 'Give thanks to Yahweh, for he is good, for his loving kindness endures forever. (Psalm 118:1)'),
  (42, '주께서 내 원수의 목전에서 내게 상을 차려 주시고 기름을 내 머리에 부으셨으니 내 잔이 넘치나이다 (시편 23:5)', 'You prepare a table before me in the presence of my enemies. You anoint my head with oil. My cup runs over. (Psalm 23:5)'),
  (43, '우리는 그가 만드신 바라 그리스도 예수 안에서 선한 일을 위하여 지으심을 받은 자니 이 일은 하나님이 전에 예비하사 우리로 그 가운데서 행하게 하려 하심이니라 (에베소서 2:10)', 'For we are his workmanship, created in Christ Jesus for good works, which God prepared before that we would walk in them. (Ephesians 2:10)'),
  (44, '너희는 내 얼굴을 찾으라 하실 때에 내가 마음으로 주께 말하되 여호와여 내가 주의 얼굴을 찾으리이다 하였나이다 (시편 27:8)', 'When you said, “Seek my face,” my heart said to you, “I will seek your face, Yahweh.” (Psalm 27:8)'),
  (45, '느헤미야가 또 그들에게 이르기를 너희는 가서 살진 것을 먹고 단 것을 마시되 준비하지 못한 자에게는 나누어 주라 이 날은 우리 주의 성일이니 근심하지 말라 여호와로 인하여 기뻐하는 것이 너희의 힘이니라 하고 (느헤미야 8:10)', 'Then he said to them, “Go your way. Eat the fat, drink the sweet, and send portions to him for whom nothing is prepared, for today is holy to our Lord. Don’t be grieved, for the joy of Yahweh is your strength.” (Nehemiah 8:10)'),
  (46, '너는 내게 부르짖으라 내가 네게 응답하겠고 네가 알지 못하는 크고 은밀한 일을 네게 보이리라 (예레미야 33:3)', '‘Call to me, and I will answer you, and will show you great and difficult things, which you don’t know.’ (Jeremiah 33:3)'),
  (47, '사람이 마음으로 자기의 길을 계획할지라도 그의 걸음을 인도하시는 이는 여호와시니라 (잠언 16:9)', 'A man’s heart plans his course, but Yahweh directs his steps. (Proverbs 16:9)'),
  (48, '우리가 알거니와 하나님을 사랑하는 자 곧 그의 뜻대로 부르심을 입은 자들에게는 모든 것이 합력하여 선을 이루느니라 (로마서 8:28)', 'We know that all things work together for good for those who love God, to those who are called according to his purpose. (Romans 8:28)'),
  (49, '공의와 인자를 따라 구하는 자는 생명과 공의와 영광을 얻느니라 (잠언 21:21)', 'He who follows after righteousness and kindness finds life, righteousness, and honor. (Proverbs 21:21)'),
  (50, '나에게 이르시기를 내 은혜가 네게 족하도다 이는 내 능력이 약한 데서 온전하여짐이라 하신지라 그러므로 도리어 크게 기뻐함으로 나의 여러 약한 것들에 대하여 자랑하리니 이는 그리스도의 능력이 내게 머물게 하려 함이라 (고린도후서 12:9)', 'He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me. (2 Corinthians 12:9)'),
  (61, '너희가 내 안에 거하고 내 말이 너희 안에 거하면 무엇이든지 원하는 대로 구하라 그리하면 이루리라 (요한복음 15:7)', 'If you remain in me, and my words remain in you, you will ask whatever you desire, and it will be done for you. (John 15:7)'),
  (62, '오직 여호와를 앙망하는 자는 새 힘을 얻으리니 독수리가 날개치며 올라감 같을 것이요 달음박질하여도 곤비하지 아니하겠고 걸어가도 피곤하지 아니하리로다 (이사야 40:31)', 'But those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint. (Isaiah 40:31)'),
  (63, '여호와여 주는 나의 등불이시니 여호와께서 나의 어둠을 밝히시리이다 (사무엘하 22:29)', 'For you are my lamp, Yahweh. Yahweh will light up my darkness. (2 Samuel 22:29)'),
  (64, '네 의를 빛 같이 나타내시며 네 공의를 정오의 빛 같이 하시리로다 (시편 37:6)', 'he will make your righteousness go out as the light, and your justice as the noon day sun. (Psalm 37:6)'),
  (65, '내 입에서 나가는 말도 이와 같이 헛되이 내게로 되돌아오지 아니하고 나의 기뻐하는 뜻을 이루며 내가 보낸 일에 형통함이니라 (이사야 55:11)', 'so is my word that goes out of my mouth: it will not return to me void, but it will accomplish that which I please, and it will prosper in the thing I sent it to do. (Isaiah 55:11)'),
  (66, '우리가 사랑함은 그가 먼저 우리를 사랑하셨음이라 (요한일서 4:19)', 'We love him, because he first loved us. (1 John 4:19)'),
  (67, '그 날에는 내가 아버지 안에, 너희가 내 안에, 내가 너희 안에 있는 것을 너희가 알리라 (요한복음 14:20)', 'In that day you will know that I am in my Father, and you in me, and I in you. (John 14:20)'),
  (68, '내가 평안히 눕고 자기도 하리니 나를 안전히 살게 하시는 이는 오직 여호와이시니이다 (시편 4:8)', 'In peace I will both lay myself down and sleep, for you, Yahweh alone, make me live in safety. (Psalm 4:8)'),
  (69, '그리스도 예수 안에 있는 속량으로 말미암아 하나님의 은혜로 값 없이 의롭다 하심을 얻은 자 되었느니라 (로마서 3:24)', 'being justified freely by his grace through the redemption that is in Christ Jesus; (Romans 3:24)'),
  (70, '여호와는 네게 복을 주시고 너를 지키시기를 원하며 (민수기 6:24)', '‘Yahweh bless you, and keep you. (Numbers 6:24)'),
  (81, '여호와는 나의 빛이요 나의 구원이시니 내가 누구를 두려워하리요 여호와는 내 생명의 능력이시니 내가 누구를 무서워하리요 (시편 27:1)', 'Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life. Of whom shall I be afraid? (Psalm 27:1)'),
  (82, '그러므로 우리가 믿음으로 의롭다 하심을 받았으니 우리 주 예수 그리스도로 말미암아 하나님과 화평을 누리자 (로마서 5:1)', 'Being therefore justified by faith, we have peace with God through our Lord Jesus Christ; (Romans 5:1)'),
  (83, '우리가 선을 행하되 낙심하지 말지니 포기하지 아니하면 때가 이르매 거두리라 (갈라디아서 6:9)', 'Let us not be weary in doing good, for we will reap in due season, if we don’t give up. (Galatians 6:9)'),
  (84, '푯대를 향하여 그리스도 예수 안에서 하나님이 위에서 부르신 부름의 상을 위하여 달려가노라 (빌립보서 3:14)', 'I press on toward the goal for the prize of the high calling of God in Christ Jesus. (Philippians 3:14)'),
  (85, '내가 여호와의 인자하심을 영원히 노래하며 주의 성실하심을 내 입으로 대대에 알게 하리이다 (시편 89:1)', 'I will sing of the loving kindness of Yahweh forever. With my mouth, I will make known your faithfulness to all generations. (Psalm 89:1)'),
  (86, '나를 원수의 수중에 가두지 아니하셨고 내 발을 넓은 곳에 세우셨음이니이다 (시편 31:8)', 'You have not shut me up into the hand of the enemy. You have set my feet in a large place. (Psalm 31:8)'),
  (87, '우리가 아직 죄인 되었을 때에 그리스도께서 우리를 위하여 죽으심으로 하나님께서 우리에 대한 자기의 사랑을 확증하셨느니라 (로마서 5:8)', 'But God commends his own love toward us, in that while we were yet sinners, Christ died for us. (Romans 5:8)'),
  (88, '네가 물 가운데로 지날 때에 내가 너와 함께 할 것이라 강을 건널 때에 물이 너를 침몰하지 못할 것이며 네가 불 가운데로 지날 때에 타지도 아니할 것이요 불꽃이 너를 사르지도 못하리니 (이사야 43:2)', 'When you pass through the waters, I will be with you; and through the rivers, they will not overflow you. When you walk through the fire, you will not be burned, and flame will not scorch you. (Isaiah 43:2)'),
  (89, '구하라 그리하면 너희에게 주실 것이요 찾으라 그리하면 찾아낼 것이요 문을 두드리라 그리하면 너희에게 열릴 것이니 (마태복음 7:7)', 'Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you. (Matthew 7:7)'),
  (90, '진리를 알지니 진리가 너희를 자유롭게 하리라 (요한복음 8:32)', 'You will know the truth, and the truth will make you free. (John 8:32)'),
  (91, '소망 중에 즐거워하며 환난 중에 참으며 기도에 항상 힘쓰며 (로마서 12:12)', 'rejoicing in hope; enduring in troubles; continuing steadfastly in prayer; (Romans 12:12)'),
  (92, '아무 것도 염려하지 말고 다만 모든 일에 기도와 간구로, 너희 구할 것을 감사함으로 하나님께 아뢰라 (빌립보서 4:6)', 'In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. (Philippians 4:6)'),
  (98, '주의 말씀의 맛이 내게 어찌 그리 단지요 내 입에 꿀보다 더 다니이다 (시편 119:103)', 'How sweet are your promises to my taste, more than honey to my mouth! (Psalm 119:103)'),
  (99, '부와 귀가 주께로 말미암고 또 주는 만물의 주재가 되사 손에 권세와 능력이 있사오니 모든 사람을 크게 하심과 강하게 하심이 주의 손에 있나이다 (역대상 29:12)', 'Both riches and honor come from you, and you rule over all! In your hand is power and might! It is in your hand to make great, and to give strength to all! (1 Chronicles 29:12)'),
  (100, '여호와여 왕이 주의 힘으로 말미암아 기뻐하며 주의 구원으로 말미암아 크게 즐거워하리이다 (시편 21:1)', 'The king rejoices in your strength, Yahweh! How greatly he rejoices in your salvation! (Psalm 21:1)'),
  (101, '하나님이 세상을 이처럼 사랑하사 독생자를 주셨으니 이는 그를 믿는 자마다 멸망하지 않고 영생을 얻게 하려 하심이라 (요한복음 3:16)', 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life. (John 3:16)'),
  (102, '이는 하늘이 땅에서 높음 같이 그를 경외하는 자에게 그의 인자하심이 크심이로다 (시편 103:11)', 'For as the heavens are high above the earth, so great is his loving kindness toward those who fear him. (Psalm 103:11)'),
  (103, '여호와는 나의 반석이시요 나의 요새시요 나를 건지시는 이시요 나의 하나님이시요 내가 그 안에 피할 나의 바위시요 나의 방패시요 나의 구원의 뿔이시요 나의 산성이시로다 (시편 18:2)', 'Yahweh is my rock, my fortress, and my deliverer; my God, my rock, in whom I take refuge; my shield, and the horn of my salvation, my high tower. (Psalm 18:2)'),
  (104, '여호와는 나의 힘과 나의 방패이시니 내 마음이 그를 의지하여 도움을 얻었도다 그러므로 내 마음이 크게 기뻐하며 내 노래로 그를 찬송하리로다 (시편 28:7)', 'Yahweh is my strength and my shield. My heart has trusted in him, and I am helped. Therefore my heart greatly rejoices. With my song I will thank him. (Psalm 28:7)'),
  (115, '여호와께서 사람의 걸음을 정하시고 그의 길을 기뻐하시나니 (시편 37:23)', 'A man’s goings are established by Yahweh. He delights in his way. (Psalm 37:23)'),
  (116, '나의 앞날이 주의 손에 있사오니 내 원수들과 나를 핍박하는 자들의 손에서 나를 건져 주소서 (시편 31:15)', 'My times are in your hand. Deliver me from the hand of my enemies, and from those who persecute me. (Psalm 31:15)'),
  (117, '너의 행사를 여호와께 맡기라 그리하면 네가 경영하는 것이 이루어지리라 (잠언 16:3)', 'Commit your deeds to Yahweh, and your plans shall succeed. (Proverbs 16:3)'),
  (118, '환난 날에 나를 부르라 내가 너를 건지리니 네가 나를 영화롭게 하리로다 (시편 50:15)', 'Call on me in the day of trouble. I will deliver you, and you will honor me. (Psalm 50:15)'),
  (119, '여호와여 나의 기도를 들으시며 나의 부르짖음에 귀를 기울이소서 내가 눈물 흘릴 때에 잠잠하지 마옵소서 나는 주와 함께 있는 나그네이며 나의 모든 조상들처럼 떠도나이다 (시편 39:12)', 'Hear my prayer, Yahweh, and give ear to my cry. Don’t be silent at my tears. For I am a stranger with you, a foreigner, as all my fathers were. (Psalm 39:12)'),
  (120, '네 길을 여호와께 맡기라 그를 의지하면 그가 이루시고 (시편 37:5)', 'Commit your way to Yahweh. Trust also in him, and he will do this: (Psalm 37:5)'),
  (121, '나는 알파와 오메가요 처음과 마지막이요 시작과 마침이라 (요한계시록 22:13)', 'I am the Alpha and the Omega, the First and the Last, the Beginning and the End. (Revelation 22:13)'),
  (122, '하나님은 우리의 피난처시요 힘이시니 환난 중에 만날 큰 도움이시라 (시편 46:1)', 'God is our refuge and strength, a very present help in trouble. (Psalm 46:1)'),
  (123, '여호와를 경외하는 것이 지혜의 근본이요 거룩하신 자를 아는 것이 명철이니라 (잠언 9:10)', 'The fear of Yahweh is the beginning of wisdom. The knowledge of the Holy One is understanding. (Proverbs 9:10)'),
  (124, '주의 궁정에서의 한 날이 다른 곳에서의 천 날보다 나은즉 악인의 장막에 사는 것보다 내 하나님의 성전 문지기로 있는 것이 좋사오니 (시편 84:10)', 'For a day in your courts is better than a thousand. I would rather be a doorkeeper in the house of my God, than to dwell in the tents of wickedness. (Psalm 84:10)'),
  (125, '나를 보내신 이가 나와 함께 하시도다 나는 항상 그가 기뻐하시는 일을 행하므로 나를 혼자 두지 아니하셨느니라 (요한복음 8:29)', 'He who sent me is with me. The Father hasn’t left me alone, for I always do the things that are pleasing to him. (John 8:29)'),
  (126, '내가 여호와께 아뢰되 주는 나의 주님이시오니 주 밖에는 나의 복이 없다 하였나이다 (시편 16:2)', 'My soul, you have said to Yahweh, “You are my Lord. Apart from you I have no good thing.” (Psalm 16:2)'),
  (127, '여호와는 마음이 상한 자를 가까이 하시고 충심으로 통회하는 자를 구원하시는도다 (시편 34:18)', 'Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit. (Psalm 34:18)'),
  (128, '주의 인자하심이 생명보다 나으므로 내 입술이 주를 찬양할 것이라 (시편 63:3)', 'Because your loving kindness is better than life, my lips shall praise you. (Psalm 63:3)'),
  (129, '여호와여 내가 주께 피하오니 내가 영원히 수치를 당하게 하지 마소서 (시편 71:1)', 'In you, Yahweh, I take refuge. Never let me be disappointed. (Psalm 71:1)'),
  (130, '나의 유리함을 주께서 계수하셨사오니 나의 눈물을 주의 병에 담으소서 이것이 주의 책에 기록되지 아니하였나이까 (시편 56:8)', 'You count my wanderings. You put my tears into your bottle. Aren’t they in your book? (Psalm 56:8)'),
  (131, '악인은 그의 길을, 불의한 자는 그의 생각을 버리고 여호와께로 돌아오라 그리하면 그가 긍휼히 여기시리라 우리 하나님께로 돌아오라 그가 너그럽게 용서하시리라 (이사야 55:7)', 'Let the wicked forsake his way, and the unrighteous man his thoughts. Let him return to Yahweh, and he will have mercy on him; and to our God, for he will freely pardon. (Isaiah 55:7)'),
  (132, '그러므로 내 백성은 내 이름을 알리라 그러므로 그 날에는 그들이 이 말을 하는 자가 나인 줄을 알리라 내가 여기 있느니라 (이사야 52:6)', 'Therefore my people shall know my name. Therefore they shall know in that day that I am he who speaks. Behold, it is I. (Isaiah 52:6)'),
  (133, '범사에 감사하라 이것이 그리스도 예수 안에서 너희를 향하신 하나님의 뜻이니라 (데살로니가전서 5:18)', 'In everything give thanks, for this is the will of God in Christ Jesus toward you. (1 Thessalonians 5:18)'),
  (134, '내 평생에 선하심과 인자하심이 반드시 나를 따르리니 내가 여호와의 집에 영원히 살리로다 (시편 23:6)', 'Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in Yahweh’s house forever. (Psalm 23:6)'),
  (145, '그러므로 너희 죄를 서로 고백하며 병이 낫기를 위하여 서로 기도하라 의인의 간구는 역사하는 힘이 큼이니라 (야고보서 5:16)', 'Confess your offenses to one another, and pray for one another, that you may be healed. The insistent prayer of a righteous person is powerfully effective. (James 5:16)'),
  (146, '내가 여호와께 바라는 한 가지 일 그것을 구하리니 곧 내가 내 평생에 여호와의 집에 살면서 여호와의 아름다움을 바라보며 그의 성전에서 사모하는 그것이라 (시편 27:4)', 'One thing I have asked of Yahweh, that I will seek after: that I may dwell in Yahweh’s house all the days of my life, to see Yahweh’s beauty, and to inquire in his temple. (Psalm 27:4)'),
  (147, '여호와여 주는 의인에게 복을 주시고 방패로 함 같이 은혜로 그를 호위하시리이다 (시편 5:12)', 'For you will bless the righteous. Yahweh, you will surround him with favor as with a shield. (Psalm 5:12)'),
  (148, '여호와여 주는 나의 하나님이시라 내가 주를 높이고 주의 이름을 찬송하오리니 주는 기사를 옛적에 정하신 뜻대로 성실함과 진실함으로 행하셨음이라 (이사야 25:1)', 'Yahweh, you are my God. I will exalt you! I will praise your name, for you have done wonderful things, things planned long ago, in complete faithfulness and truth. (Isaiah 25:1)'),
  (149, '내 아들아 네 마음을 내게 주며 네 눈으로 내 길을 즐거워할지어다 (잠언 23:26)', 'My son, give me your heart; and let your eyes keep in my ways. (Proverbs 23:26)'),
  (150, '여호와는 나의 사랑이시요 나의 요새이시요 나의 산성이시요 나를 건지시는 이시요 나의 방패이시니 내가 그에게 피하였고 그가 내 백성을 내게 복종하게 하셨나이다 (시편 144:2)', 'my loving kindness, my fortress, my high tower, my deliverer, my shield, and he in whom I take refuge; who subdues my people under me. (Psalm 144:2)'),
  (151, '내 영이 내 속에서 상할 때에도 주께서 내 길을 아셨나이다 내가 가는 길에 그들이 나를 잡으려고 올무를 숨겼나이다 (시편 142:3)', 'When my spirit was overwhelmed within me, you knew my route. On the path in which I walk, they have hidden a snare for me. (Psalm 142:3)'),
  (152, '오직 성령의 열매는 사랑과 희락과 화평과 오래 참음과 자비와 양선과 충성과 (갈라디아서 5:22)', 'But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, (Galatians 5:22)'),
  (153, '그러나 여호와께서 기다리시나니 이는 너희에게 은혜를 베풀려 하심이요 일어나시리니 이는 너희를 긍휼히 여기려 하심이라 대저 여호와는 정의의 하나님이심이라 그를 기다리는 자마다 복이 있도다 (이사야 30:18)', 'Therefore Yahweh will wait, that he may be gracious to you; and therefore he will be exalted, that he may have mercy on you, for Yahweh is a God of justice. Blessed are all those who wait for him. (Isaiah 30:18)'),
  (154, '내 영혼을 소생시키시고 자기 이름을 위하여 의의 길로 인도하시는도다 (시편 23:3)', 'He restores my soul. He guides me in the paths of righteousness for his name’s sake. (Psalm 23:3)'),
  (155, '하나님이여 주는 나의 하나님이시라 내가 간절히 주를 찾되 물이 없어 마르고 황폐한 땅에서 내 영혼이 주를 갈망하며 내 육체가 주를 앙모하나이다 (시편 63:1)', 'God, you are my God. I will earnestly seek you. My soul thirsts for you. My flesh longs for you, in a dry and weary land, where there is no water. (Psalm 63:1)'),
  (156, '너의 하나님 여호와가 너의 가운데에 계시니 그는 구원을 베푸실 전능자이시라 그가 너로 말미암아 기쁨을 이기지 못하시며 너를 잠잠히 사랑하시며 너로 말미암아 즐거이 부르며 기뻐하시리라 하리라 (스바냐 3:17)', 'Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing. (Zephaniah 3:17)'),
  (157, '끝으로 너희가 주 안에서와 그 힘의 능력으로 강건하여지고 (에베소서 6:10)', 'Finally, be strong in the Lord, and in the strength of his might. (Ephesians 6:10)'),
  (158, '왕이신 나의 하나님이여 내가 주를 높이고 영원히 주의 이름을 송축하리이다 (시편 145:1)', 'I will exalt you, my God, the King. I will praise your name forever and ever. (Psalm 145:1)'),
  (159, '이는 나 여호와 너의 하나님이 네 오른손을 붙들고 네게 이르기를 두려워하지 말라 내가 너를 도우리라 할 것임이니라 (이사야 41:13)', 'For I, Yahweh your God, will hold your right hand, saying to you, ‘Don’t be afraid. I will help you.’ (Isaiah 41:13)'),
  (160, '할렐루야, 여호와의 종들아 찬양하라 여호와의 이름을 찬양하라 (시편 113:1)', 'Praise Yah! Praise, you servants of Yahweh, praise Yahweh’s name. (Psalm 113:1)'),
  (161, '주께서 나의 등불을 켜심이여 여호와 내 하나님이 내 흑암을 밝히시리이다 (시편 18:28)', 'For you will light my lamp, Yahweh. My God will light up my darkness. (Psalm 18:28)'),
  (162, '예수께서 여자에게 이르시되 네 믿음이 너를 구원하였으니 평안히 가라 하시니라 (누가복음 7:50)', 'He said to the woman, “Your faith has saved you. Go in peace.” (Luke 7:50)'),
  (163, '여호와는 내 편이시라 내가 두려워하지 아니하리니 사람이 내게 어찌할까 (시편 118:6)', 'Yahweh is on my side. I will not be afraid. What can man do to me? (Psalm 118:6)'),
  (164, '너희는 이 세대를 본받지 말고 오직 마음을 새롭게 함으로 변화를 받아 하나님의 선하시고 기뻐하시고 온전하신 뜻이 무엇인지 분별하도록 하라 (로마서 12:2)', 'Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God. (Romans 12:2)'),
  (171, '그러므로 하나님의 능하신 손 아래에서 겸손하라 때가 되면 너희를 높이시리라 (베드로전서 5:6)', 'Humble yourselves therefore under the mighty hand of God, that he may exalt you in due time; (1 Peter 5:6)'),
  (175, '여호와께서 내 간구를 들으셨음이여 여호와께서 내 기도를 받으시리로다 (시편 6:9)', 'Yahweh has heard my supplication. Yahweh accepts my prayer. (Psalm 6:9)'),
  (176, '여호와 내 하나님이여 내가 주께 피하오니 나를 쫓아오는 모든 자들에게서 나를 구원하여 내소서 (시편 7:1)', 'Yahweh, my God, I take refuge in you. Save me from all those who pursue me, and deliver me, (Psalm 7:1)'),
  (177, '내게로 돌이키사 내게 은혜를 베푸소서 주의 종에게 힘을 주시고 주의 여종의 아들을 구원하소서 (시편 86:16)', 'Turn to me, and have mercy on me! Give your strength to your servant. Save the son of your servant. (Psalm 86:16)'),
  (178, '여호와는 선하시니 그의 인자하심이 영원하고 그의 성실하심이 대대에 이르리로다 (시편 100:5)', 'For Yahweh is good. His loving kindness endures forever, his faithfulness to all generations. (Psalm 100:5)'),
  (179, '여호와는 나의 능력과 찬송이시요 또 나의 구원이 되셨도다 (시편 118:14)', 'Yah is my strength and song. He has become my salvation. (Psalm 118:14)'),
  (180, '그가 궁핍한 자의 오른쪽에 서사 그의 영혼을 심판하려 하는 자들에게서 구원하실 것임이로다 (시편 109:31)', 'For he will stand at the right hand of the needy, to save him from those who judge his soul. (Psalm 109:31)'),
  (181, '내가 산 자들의 땅에서 여호와의 선하심을 보게 될 줄 확실히 믿었도다 (시편 27:13)', 'I am still confident of this: I will see the goodness of Yahweh in the land of the living. (Psalm 27:13)'),
  (182, '나의 힘이시여 내가 주께 찬송하오리니 하나님은 나의 요새이시며 나를 긍휼히 여기시는 하나님이심이니이다 (시편 59:17)', 'To you, my strength, I will sing praises. For God is my high tower, the God of my mercy. (Psalm 59:17)'),
  (183, '여호와여 주의 증거들이 매우 확실하고 거룩함이 주의 집에 합당하니 여호와는 영원무궁하시리이다 (시편 93:5)', 'Your statutes stand firm. Holiness adorns your house, Yahweh, forever more. (Psalm 93:5)'),
  (184, '믿음은 바라는 것들의 실상이요 보이지 않는 것들의 증거니 (히브리서 11:1)', 'Now faith is assurance of things hoped for, proof of things not seen. (Hebrews 11:1)'),
  (185, '그러므로 우리가 담대히 말하되 주는 나를 돕는 이시니 내가 무서워하지 아니하겠노라 사람이 내게 어찌하리요 하노라 (히브리서 13:6)', 'So that with good courage we say, “The Lord is my helper. I will not fear. What can man do to me?” (Hebrews 13:6)'),
  (186, '너희가 기도할 때에 무엇이든지 믿고 구하는 것은 다 받으리라 하시니라 (마태복음 21:22)', 'All things, whatever you ask in prayer, believing, you will receive. (Matthew 21:22)'),
  (187, '여호와여 내 젊은 시절의 죄와 허물을 기억하지 마시고 주의 인자하심을 따라 주께서 나를 기억하시되 주의 선하심으로 하옵소서 (시편 25:7)', 'Don’t remember the sins of my youth, nor my transgressions. Remember me according to your loving kindness, for your goodness’ sake, Yahweh. (Psalm 25:7)'),
  (188, '하나님이여 내 속에 정한 마음을 창조하시고 내 안에 정직한 영을 새롭게 하소서 (시편 51:10)', 'Create in me a clean heart, O God. Renew a right spirit within me. (Psalm 51:10)'),
  (189, '여호와는 나의 산업과 나의 잔의 소득이시니 나의 분깃을 지키시나이다 (시편 16:5)', 'Yahweh assigned my portion and my cup. You made my lot secure. (Psalm 16:5)'),
  (190, '내가 항상 주와 함께 하니 주께서 내 오른손을 붙드셨나이다 (시편 73:23)', 'Nevertheless, I am continually with you. You have held my right hand. (Psalm 73:23)'),
  (191, '여호와께서 나를 위하여 보상해 주시리이다 여호와여 주의 인자하심이 영원하오니 주의 손으로 지으신 것을 버리지 마옵소서 (시편 138:8)', 'Yahweh will fulfill that which concerns me; your loving kindness, Yahweh, endures forever. Don’t forsake the works of your own hands. (Psalm 138:8)'),
  (192, '사람아 주께서 선한 것이 무엇임을 네게 보이셨나니 여호와께서 네게 구하시는 것은 오직 정의를 행하며 인자를 사랑하며 겸손하게 네 하나님과 함께 행하는 것이 아니냐 (미가 6:8)', 'He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God? (Micah 6:8)'),
  (193, '내가 주의 법을 어찌 그리 사랑하는지요 내가 그것을 종일 작은 소리로 읊조리나이다 (시편 119:97)', 'How I love your law! It is my meditation all day. (Psalm 119:97)'),
  (199, '이것들이 아침마다 새로우니 주의 성실하심이 크시도소이다 (예레미야애가 3:23)', 'They are new every morning. Great is your faithfulness. (Lamentations 3:23)')
) as v(order_no, kr, en)
where dv.order_no = v.order_no and dv.type = 'bible';
